CREATE DATABASE ProjectKB;

USE ProjectKB;

CREATE TABLE scores (
	id SERIAL PRIMARY KEY,
	version VARCHAR(16) NOT NULL,
	preset TINYINT UNSIGNED NOT NULL,
	playerName VARCHAR(16) NOT NULL,
	timestamp TIMESTAMP NOT NULL,
	score DOUBLE NOT NULL,
	level DOUBLE NOT NULL
);
